const sectionDescription = [
'Biblioteca',
'Biotério',
'Call Center',
'Captação',
'Central de Estágio',
'Central de Eventos',
'Clinica da Psicologia',
'Clinica Odontológica',
'Compras',
'Compras - Almoxarifado',
'Curso de Administração',
'Curso de Arquitetura e Urbanismo',
'Curso de Biomedicina',
'Curso de Ciências Biológicas',
'Curso de Direito',
'Curso de Educação Física',
'Curso de Enfermagem',
'Curso de Engenharia Ambiental',
'Curso de Engenharia Civil',
'Curso de Engenharia de Produção',
'Curso de Engenharia Mecânica',
'Curso de Engenharia Quimica',
'Curso de Farmácia',
'Curso de Fisioterapia',
'Curso de Letras',
'Curso de Matemática - EAD',
'Curso de Medicina',
'Curso de Medicina Veterinária',
'Curso de Nutrição',
'Curso de Pedagogia',
'Curso de Psicologia',
'Curso de Serviço Social',
'Curso de Sistemas de Informação',
'Curso de Tecnologia em Estética e Cosméticos',
'Curso Superior de Tecnologia em Segurança no Trabalho',
'ENADE - Construindo Resultados',
'Financeiro',
'HOVET - Clínicos',
'HOVET - Mini Fazenda',
'HOVET Administração ',
'HOVET Financeiro',
'Humanas',
'I - Clínica de Fisioterapia e Estética',
'I - Complexo Esportivo (PAEC)',
'I - Programa de Medicina e Bem Estar Animal',
'I - Programa de Odontologia',
'I - Programas de Residência Médica',
'I - Programas de Residência Multiprofissional',
'II - Central de Relacionamento',
'II - CST Gestão Hospitalar',
'II - Curso de Ciências Contábeis',
'II - Curso de Filosofia',
'II - Curso de Geografia',
'II - Curso de História',
'II - Curso de Jornalismo',
'II - Curso de Odontologia',
'II - Curso de Publicidade e Propaganda',
'II - Curso de Radio e TV',
'II - Cursos Tecnológicos de Gestão',
'II - Programa de Ciências Humanas',
'II - Projeto Camp Norte',
'Infraestrutura - Conservação e Limpeza',
'Infraestrutura - Engenharia e Manutenção',
'Infraestrutura - Frotas/Expedição',
'Infraestrutura - Laboratórios Multidisciplinares',
'Infraestrutura - Multimeios',
'Infraestrutura - Portaria',
'Juridico - Campus ll',
'Marketing',
'NPJ - Nucleo de praticas juridicas',
'Planejamento e Controle',
'Pós-Graduação Lato Sensu',
'Programa Ciências da Saúde',
'Programa de Medicina Populacional',
'Programa Implanto',
'Recursos Humanos',
'Reitoria',
'Secretaria de Registros e Diplomas',
'Secretaria Geral',
'SESMT',
'Tecnologia da Informação',
'Unisa Digital - Administrativo',
'Unisa Digital - Bom Jesus da Lapa - BA',
'Unisa Digital - Desenho Educacional',
'Unisa Digital - Disciplinas Web',
'Unisa Digital - Gestão de Mídias',
'Unisa Digital - Logistica de Provas',
'Unisa Digital - Sistema Tutorial',
'Unisa Digital - Sistema Tutorial Presencial',
'Unisa Digital - Vila Maria',
'Vestibular',
];
export default sectionDescription;